version: '2'

volumes:
  jenkins_data:
  sonarqube_data:

services:
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    ports:
      - "10000:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
    user: root
    volumes:
      - ./realm-export.json:/import/ecom.json
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    user: root
    ports:
      - "11000:8080"
    volumes:
      - jenkins_data/:/var/jenkins_home
  sonar:
    container_name: sonar
    image: sonarqube:7.8-community
    ports:
      - "11001:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
